on:
  schedule:
    - cron:  '0 1 * * *'
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build the data and create local changes
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: x64
    - name: Install requirements
      run: |
        - curl -L https://clis.ng.bluemix.net/download/bluemix-cli/latest/linux64 | tar -zx
        - chmod -R u+x ./Bluemix_CLI/bin

    - name: Process Data
      run: |
        - ./script/latest-smdg.py
        - ./script/prepare.sh
        - pytest .

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git diff --quiet && git diff --staged --quiet || git commit -a -m "Auto-update of the data packages"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.gh }}
  deploy:
    needs: update
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: ./script/deploy.sh
      env:
        APIKEY: ${{secrets.apikey}}
        CF_ORG: ${{secrets.cf_org}}
        CF_SPACE: ${{secrets.cf_space}}
